spring.application.name=department

# Server Port
server.port=8082


# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Fetch registry every 30 seconds
eureka.client.registry-fetch-interval-seconds=30

# Heartbeat every 5 seconds
eureka.instance.lease-renewal-interval-in-seconds=5

# Expire instance after 10 seconds if no heartbeat
eureka.instance.lease-expiration-duration-in-seconds=10

# Actuator Configuration
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DB configurations
spring.datasource.url=jdbc:mysql://localhost:3306/practice
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configurations
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5